= Introduction

== Change Control History

[change control table here]
[width="80%",options="header",caption=""]
|====================
|Version Number | Date of Issue  | Author(s)  | Brief Description of Change(s)
| 4.1.64 | 2023-01-15 | ((Jonathan Pritchard)) | Initial Version
|====================

== Introduction
The International Hydrographic Organization (IHO) Test Data Sets (TDS) for Electronic Chart and Display Information System (ECDIS) have been produced to fulfil the requirement for a data set necessary to accomplish all ECDIS testing requirements as outlined in the IEC 61174 standard.

The TDS has been published as IHO Publication Number 164 and consists of numerous data sets required for testing as well as this guide, the TDS Instruction Manual (TIM). The TIM provides supporting documentation about the organization, understanding, and use of the ENC TDS and is intended to be used along with the data sets included in the TDS. It aims to provide appropriate comments about each test including the information about the most suitable data elements, their location and the expected test results.


== Acknowledgments
Edition 1.0.0 and its subsequent clarifications has been produced with assistance from many expert contributors and members of the IHO S-100 Working Group (S-100WG) and IHO Nautical Information Pr working group (NIPWG). Their input during the revision process has been invaluable.

== Acronyms and Terms
This publication makes extensive use of terms and acronyms described in the IHO S-32 Standard. Additionally, the following acronyms are frequently used:

TDS – Test Data Sets
TIM - TDS Instruction Manual
EUT – Equipment Under Test

== References
This publication provides tests based on the requirements documented in IHO standards. References to the source for a specific test are provided within this document. As specified in the IEC 61174 standard the tests provided are used to ensure conformance to the ECDIS requirements laid out in the IMO performance standard for ECDIS.

Normative References:
IHO S-100 Part 9 - Specifications for Chart Content and Display Aspects of ECDIS
IHO S-101 Standard for electronic navigational charts
IHO S-100 Part 15 - Data Protection Scheme
IHO S-100 Part 17 - Metadata

Informative References:
IHO S-32 - Hydrographic Dictionary (provides ECDIS related definitions)
IHO S-65 – ENC Production Guidance

== Key Documents, Organizations and Relationships
The development and application of the TDS involves several organizations and related specifications (see Figure 1). The TDS was produced by the IHO to allow for the complete testing of ECDIS equipment (hardware and software) vis-à-vis the ECDIS Performance Standard.

The ECDIS Performance Standard is specified by the International Maritime Organization (IMO) in MSC.232(82), and methods for testing this standard are the responsibility of the International Electrotechnical Commission (IEC) which publishes these requirements in document IEC 61174.

*Figure 1 is here*

All standards are subject to revision. Therefore, users of these standards must use the most recent editions of the standards indicated below. Members of IEC and ISO maintain registers of currently valid international standards.

== Structure of the Instruction Manual
This document consists of an introduction followed by tests arranged over a number of sections in a task based layout. All tests are listed in a common format which is described in the example later in this section. The tests are arranged in the following structure.

* S-100 ECDIS tests [desc]
* S-57 tests
* Dual Fuel mode specific tests

== Organization and Coverage of the TDS
The TDS contains a named folder/directory for each section of the TIM which requires test data.

Depending on the test requirement, the folder may also contain an S100_ROOT directory containing the files of the exchange set (CATALOG.XML, plus any updates and supporting files in a structure conforming to S-100 Part 17).

The TDS data for encrypted data, located in section 2.5, contains multiple exchange sets, each with their own ENC_ROOT directory and full test scripts describing how to use the data. The location (or path) of ENC exchange set and/or ENC cell will be indicated using italic notation, e.g. 2.1.1 Power Up\ENC_ROOT\GB4X000.000. The manual frequently refers to test data “location” using a drive prefix of “D:” – this is because usually the test data is loaded from a hard media drive on the ECDIS but this may vary between systems and according to how the data is being imported onto the ECDIS. To conform to the directory structure as defined in S-57 Appendix B.1 Section 5.4.3, the ENC_ROOT directory should be located in the media’s root directory. This should be viewed as a requirement. However, in practical terms, many systems can “browse” and load files from almost any location and removable media. Consult with the equipment manufacturer for further information.


== Required Test Items and Use of the TDS
This section lists the items required for the execution of Tests specified in this document and how the TDS should be used. The following items are required:

_1. IHO ECDIS Presentation Library contained in S-52, Annex A including an ECDIS Chart 1 and colour differentiation diagrams. If the manufacturer provides his own presentation library, Chart 1 has to be adapted accordingly._

2. IHO S-64 test data sets for ECDIS which includes ENC data, both encrypted and unencrypted, and its updates, together with the associated instruction manual.

_3. SENC test data sets, if supported from each SENC distributor._ *tbc*

_The first item in the list, the IHO ECDIS Presentation Library (S-52, Annex A) including an ECDIS Chart 1 and colour differentiation diagrams must be acquired and installed on the equipment under test (EUT) by the manufacturer, prior to the beginning of the tests._

The second item, the IHO TDS, is provided as part of S-164, including the encrypted data and its test scripts. This document is to be considered the “Instruction Manual”. The IHO TDS may be upgraded from time to time to correct residual anomalies and ensure that the results of the tests conform to the description in this Manual.

It is important to ensure that the tests are conducted with the latest version posted on the IHO web site at http://www.iho.int > (ENCs & ECDIS). The version number (1.0.0) will remain the same as long as the corrections do not impact this document.

_The third item on the list, SENC test data set, if supported, must be provided by the manufacturer._

== Notes on ECDIS Screen Samples [needed?]
The following notes may be applicable to the ECDIS screen samples within this document:

*Light Descriptions*
Between the light characteristics abbreviation and the colour attribute it is acceptable for the ECDIS to display the light description text with or without a space. There must be a space between the light colour and signal period, for example:

Fl W 30s7m10M or FlW 30s7m10M are both acceptable options

Further details are given in S-52 Presentation Library edition 4.0.2 Part 1 10.6.3 Light Description Text Strings

*Light Descriptions for Sectored Lights*
The light description text string is normally not used for sector lights because it would cause clutter however OEMs are not prevented from doing so. Where OEMs have displayed the text strings in their ECDIS they must provide a method to select/deselect them from the ECDIS display. Further details are available in S-52 Presentation Library edition 4.0.2 Part 1 LIGHTS06 conditional symbology procedure.

*Centred Symbols*
There is no algorithm specified by S-52 for OEMs to calculate the centre of an area. Therefore depending on the ECDIS there maybe instances where the centred symbol is not visible. If the centred symbol is not visible in the ECDIS display the zoom level should be increased until the symbol becomes visible.

== Notes on Dual Fuel mode and ECDIS transition
*Notes here on how transition works, and how that relates to ECDIS testing etc...*
